// ecommerce-qwik/src/components/product/add-to-cart.tsx
import { component$, $ } from '@builder.io/qwik';
import type { Product } from '~/types';
import { useCartStore } from '~/lib/cart-store';
import { addItemToCart } from '~/lib/cart-actions';

interface AddToCartProps {
  product: Product;
}

export default component$<AddToCartProps>(({ product }) => {
  const store = useCartStore();

  const handleAddToCart = $((event: Event) => {
    event.preventDefault();
    addItemToCart(store, product);
  });

  return (
    <button
      onClick$={handleAddToCart}
      class="bg-purple-600 text-white px-3 py-1 rounded text-sm hover:bg-purple-700 transition-colors"
    >
      Add to Cart
    </button>
  );
});

// ecommerce-astro/src/components/AddToCart.tsx
import type { Product } from '../types';
import { useCartStore } from '../lib/cart-store';
import { useEffect, useState } from 'react';

interface AddToCartProps {
  product: Product;
}

export default function AddToCart({ product }: AddToCartProps) {
  const [mounted, setMounted] = useState(false);
  const addItem = useCartStore((state) => state.addItem);

  useEffect(() => {
    setMounted(true);
  }, []);

  const handleAddToCart = (e: React.MouseEvent) => {
    e.preventDefault();
    if (mounted) {
      addItem(product);
    }
  };

  return (
    <button
      onClick={handleAddToCart}
      className="bg-green-600 text-white px-3 py-1 rounded text-sm hover:bg-green-700 transition-colors"
      disabled={!mounted}
    >
      Add to Cart
    </button>
  );
}
