// ecommerce-qwik/src/components/cart/cart-button.tsx
import { component$, useComputed$ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import { ShoppingCartIcon } from 'lucide-qwik';
import { useCart } from '~/lib/cart-context';
import { getTotalItems } from '~/lib/cart-actions';

export default component$(() => {
  const cart = useCart();

  const totalItems = useComputed$(() => getTotalItems(cart));

  return (
    <Link 
      href="/cart" 
      class="relative p-2 text-gray-700 hover:text-gray-900 transition-colors"
    >
      <ShoppingCartIcon class="w-6 h-6" />
      {totalItems.value > 0 && (
        <span class="absolute -top-1 -right-1 bg-blue-600 text-white rounded-full w-5 h-5 text-xs flex items-center justify-center">
          {totalItems.value}
        </span>
      )}
    </Link>
  );
});

// ecommerce-astro/src/components/CartButton.tsx
import { ShoppingCart } from 'lucide-react';
import { useCartStore } from '../lib/cart-store';
import { useEffect, useState } from 'react';

export default function CartButton() {
  const [mounted, setMounted] = useState(false);
  const totalItems = useCartStore((state) => state.getTotalItems());

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <a 
      href="/cart" 
      className="relative flex h-10 w-10 items-center justify-center rounded-full border border-gray-300 bg-white text-gray-700 transition-colors hover:bg-gray-50 hover:text-gray-900"
    >
      <ShoppingCart className="h-5 w-5" />
      {mounted && totalItems > 0 && (
        <span className="absolute -top-2 -right-2 flex h-5 w-5 items-center justify-center rounded-full bg-blue-600 text-xs font-medium text-white">
          {totalItems}
        </span>
      )}
    </a>
  );
}
