// ecommerce-nextjs/src/app/product/[id]/page.tsx
import { notFound } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import { getProduct } from '@/lib/products';
import { AddToCartButton } from './add-to-cart-button';

type Props = {
  params: { id: string };
};

export default async function ProductPage({ params }: Props) {
  const product = await getProduct(params.id);

  if (!product) notFound();

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <Link 
        href="/" 
        className="text-blue-600 hover:text-blue-800 mb-6 inline-block"
      >
        ← Back to products
      </Link>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Product Image */}
        <div className="aspect-square bg-gray-100 rounded-lg overflow-hidden">
          <Image
            src={product.image}
            alt={product.name}
            width={600}
            height={600}
            className="w-full h-full object-cover"
            priority
          />
        </div>

        {/* Product Info */}
        <div>
          <h1 className="text-3xl font-bold text-gray-900 mb-4">
            {product.name}
          </h1>
          
          <p className="text-gray-600 mb-6">
            {product.description}
          </p>
          
          <div className="text-2xl font-bold text-gray-900 mb-6">
            ${product.price}
          </div>

          <AddToCartButton product={product} />
        </div>
      </div>
    </div>
  );
}

// ecommerce-qwik/src/routes/product/[id]/index.tsx
import { component$ } from '@builder.io/qwik';
import { routeLoader$, Link } from '@builder.io/qwik-city';
import type { DocumentHead } from '@builder.io/qwik-city';
import { getProduct } from '~/lib/products';
import AddToCart from '~/components/product/add-to-cart';

export const useProductLoader = routeLoader$(async (requestEvent) => {
  const productId = requestEvent.params.id;
  const product = getProduct(productId);
  
  if (!product) {
    throw requestEvent.error(404, 'Product not found');
  }
  
  return product;
});

export default component$(() => {
  const product = useProductLoader();

  return (
    <div class="max-w-6xl mx-auto px-4 py-8">
      {/* Back Link - ідентичний до Next.js */}
      <Link 
        href="/" 
        class="text-blue-600 hover:text-blue-800 mb-6 inline-block"
      >
        ← Back to products
      </Link>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Product Image - ідентичний до Next.js */}
        <div class="aspect-square bg-gray-100 rounded-lg overflow-hidden">
          <img
            src={product.value.image}
            alt={product.value.name}
            class="w-full h-full object-cover"
            width={600}
            height={600}
          />
        </div>

        {/* Product Info - ідентичний до Next.js */}
        <div>
          <h1 class="text-3xl font-bold text-gray-900 mb-4">
            {product.value.name}
          </h1>
          
          <p class="text-gray-600 mb-6">
            {product.value.description}
          </p>
          
          <div class="text-2xl font-bold text-gray-900 mb-6">
            ${product.value.price}
          </div>

          {/* Large Add to Cart Button */}
          <AddToCart product={product.value} variant="large" />
        </div>
      </div>
    </div>
  );
});

export const head: DocumentHead = ({ resolveValue }) => {
  const product = resolveValue(useProductLoader);
  return {
    title: `${product.name} - TechStore`,
    meta: [
      {
        name: 'description',
        content: product.description,
      },
    ],
  };
};
