// ecommerce-nextjs/src/app/cart/page.tsx
'use client';

import { useCartStore } from '@/lib/cart-store';
import Image from 'next/image';
import Link from 'next/link';

export default function CartPage() {
  const { items, updateQuantity, removeItem, getTotalPrice} = useCartStore();
  const totalPrice = getTotalPrice();

  if (items.length === 0) {
    return (
      <div className="max-w-6xl mx-auto px-4 py-16 text-center">
        <h1 className="text-2xl font-bold mb-4">Your cart is empty</h1>
        <Link 
          href="/" 
          className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition-colors"
        >
          Continue Shopping
        </Link>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-8">Shopping Cart</h1>
      
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-4">
          {items.map((item) => (
            <div key={item.product.id} className="bg-white p-4 rounded-lg border">
              <div className="flex items-center space-x-4">
                <Image
                  src={item.product.image}
                  alt={item.product.name}
                  width={80}
                  height={80}
                  className="rounded-lg"
                />
                
                <div className="flex-1">
                  <h3 className="font-medium">{item.product.name}</h3>
                  <p className="text-gray-600">${item.product.price}</p>
                </div>
                
                <div className="flex items-center space-x-2">
                  <button
                    onClick={() => updateQuantity(item.product.id, item.quantity - 1)}
                    className="bg-gray-200 px-2 py-1 rounded"
                  >
                    -
                  </button>
                  <span className="px-3">{item.quantity}</span>
                  <button
                    onClick={() => updateQuantity(item.product.id, item.quantity + 1)}
                    className="bg-gray-200 px-2 py-1 rounded"
                  >
                    +
                  </button>
                </div>
                
                <button
                  onClick={() => removeItem(item.product.id)}
                  className="text-red-600 hover:text-red-800"
                >
                  Remove
                </button>
              </div>
            </div>
          ))}
        </div>

        <div className="bg-white p-6 rounded-lg border h-fit">
          <h2 className="text-xl font-bold mb-4">Order Summary</h2>
          <div className="space-y-2 mb-4">
            <div className="flex justify-between">
              <span>Subtotal:</span>
              <span>${totalPrice.toFixed(2)}</span>
            </div>
            <div className="flex justify-between">
              <span>Shipping:</span>
              <span>Free</span>
            </div>
            <div className="border-t pt-2 flex justify-between font-bold">
              <span>Total:</span>
              <span>${totalPrice.toFixed(2)}</span>
            </div>
          </div>
          
          <Link
            href="/checkout"
            className="w-full bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700 transition-colors block text-center"
          >
            Proceed to Checkout
          </Link>
        </div>
      </div>
    </div>
  );
}

// ecommerce-qwik/src/routes/cart/index.tsx
import { component$, useComputed$, $ } from '@builder.io/qwik';
import { Link } from '@builder.io/qwik-city';
import type { DocumentHead } from '@builder.io/qwik-city';
import { useCart } from '~/lib/cart-context';
import {
  updateItemQuantity,
  removeItemFromCart,
  getTotalPrice
} from '~/lib/cart-actions';

export default component$(() => {
  const cart = useCart();

  const totalPrice = useComputed$(() => getTotalPrice(cart));

  const handleUpdate = $(async (productId: string, quantity: number) => {
    await updateItemQuantity(cart, productId, quantity);
  });

  const handleRemove = $(async (productId: string) => {
    await removeItemFromCart(cart, productId);
  });

  if (cart.items.length === 0) {
    return (
      <div class="max-w-6xl mx-auto px-4 py-16 text-center">
        <h1 class="text-2xl font-bold mb-4">Your cart is empty</h1>
        <Link 
          href="/" 
          class="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition-colors"
        >
          Continue Shopping
        </Link>
      </div>
    );
  }

  return (
    <div class="max-w-6xl mx-auto px-4 py-8">
      <h1 class="text-3xl font-bold mb-8">Shopping Cart</h1>
      
      <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div class="lg:col-span-2 space-y-4">
          {cart.items.map((item) => (
            <div key={item.product.id} class="bg-white p-4 rounded-lg border">
              <div class="flex items-center space-x-4">
                <img
                  src={item.product.image}
                  alt={item.product.name}
                  class="w-20 h-20 rounded-lg object-cover"
                  width={80}
                  height={80}
                />
                
                <div class="flex-1">
                  <h3 class="font-medium">{item.product.name}</h3>
                  <p class="text-gray-600">${item.product.price}</p>
                </div>
                
                <div class="flex items-center space-x-2">
                  <button
                    onClick$={() => handleUpdate(item.product.id, item.quantity - 1)}
                    class="bg-gray-200 px-2 py-1 rounded hover:bg-gray-300"
                  >
                    -
                  </button>
                  <span class="px-3">{item.quantity}</span>
                  <button
                    onClick$={() => handleUpdate(item.product.id, item.quantity + 1)}
                    class="bg-gray-200 px-2 py-1 rounded hover:bg-gray-300"
                  >
                    +
                  </button>
                </div>
                
                <button
                  onClick$={() => handleRemove(item.product.id)}
                  class="text-red-600 hover:text-red-800"
                >
                  Remove
                </button>
              </div>
            </div>
          ))}
        </div>

        <div class="bg-white p-6 rounded-lg border h-fit">
          <h2 class="text-xl font-bold mb-4">Order Summary</h2>
          <div class="space-y-2 mb-4">
            <div class="flex justify-between">
              <span>Subtotal:</span>
              <span>${totalPrice.value.toFixed(2)}</span>
            </div>
            <div class="flex justify-between">
              <span>Shipping:</span>
              <span>Free</span>
            </div>
            <div class="border-t pt-2 flex justify-between font-bold">
              <span>Total:</span>
              <span>${totalPrice.value.toFixed(2)}</span>
            </div>
          </div>
          
          <Link
            href="/checkout"
            class="w-full bg-blue-600 text-white py-3 rounded-lg hover:bg-blue-700 transition-colors block text-center"
          >
            Proceed to Checkout
          </Link>
        </div>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: 'Shopping Cart - TechStore',
  meta: [
    {
      name: 'description',
      content: 'Your shopping cart items',
    },
  ],
};
